nameOverride: ""
fullnameOverride: ""

image:
  repository: gomin/auth
  tag: ""
  pullPolicy: Always

replicaCount: 1

imagePullSecrets: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: ClusterIP
  port: 5000

migrations:
  enabled: true

seedSecrets:
  gatewayServiceSecret: ""
  communicationServiceSecret: ""
  authServiceSecret: ""

resources:
  requests:
    cpu: 300m
    memory: 192Mi
  limits:
    cpu: 600m
    memory: 384Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

env: {}

envFrom:
  - secretRef:
      name: auth-secret
