
export const ChatPermission = {
  general: {
    SEND_MESSAGES: 'SEND_MESSAGES',
    SEND_MEDIA: 'SEND_MEDIA',
    SEND_STICKERS: 'SEND_STICKERS',
    PIN_MESSAGES: 'PIN_MESSAGES',
    DELETE_MESSAGES: 'DELETE_MESSAGES',
    EDIT_MESSAGES: 'EDIT_MESSAGES',
    MENTION_USERS: 'MENTION_USERS',
    UPDATE_CHAT: 'UPDATE_CHAT',
    ADD_USERS: 'ADD_USERS',
  },
  admin: {
    MANAGE_CHAT: 'MANAGE_CHAT',
    MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
    MANAGE_MEMBERS: 'MANAGE_MEMBERS',
    BAN_USERS: 'BAN_USERS',
    PROMOTE_USERS: 'PROMOTE_USERS',
    DEMOTE_USERS: 'DEMOTE_USERS',
    DELETE_CHAT: 'DELETE_CHAT',
    REMOVE_USER: 'REMOVE_USER',
    DELETE_USER_MESSAGES: 'DELETE_USER_MESSAGES',
  },
  channel: {
    POST_MESSAGES: 'POST_MESSAGES',
    EDIT_CHANNEL_INFO: 'EDIT_CHANNEL_INFO',
    INVITE_LINK: 'INVITE_LINK',
  }
}
