export const TABLE_CHATS = 'CHATS';
export const TABLE_CHAT_MEMBERS = 'CHAT_MEMBERS';
export const TABLE_MESSAGES = 'MESSAGES';
export const TABLE_SENDER_KEYS = 'SENDER_KEYS';
export const TABLE_MESSAGE_STATUS = 'MESSAGE_STATUS';
export const TABLE_MESSAGE_REACTIONS = 'MESSAGE_REACTIONS';
