apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.apps }}
  annotations:
    linkerd.io/inject: enabled
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    gomin/namespace-type: apps
