nameOverride: ""
fullnameOverride: ""

image:
  repository: gomin/web
  tag: ""
  pullPolicy: Always

replicaCount: 1

imagePullSecrets: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: app.84.247.133.45.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - app.84.247.133.45.nip.io
      secretName: web-tls

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
