nameOverride: ""
fullnameOverride: ""

image:
  repository: gomin/api-gateway
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: api.84.247.133.45.nip.io # Replace with your external IP
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env: {}

envFrom:
  - secretRef:
      name: api-gateway-secret
