export const USERS_SERVICE = 'USER_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';
export const PERMISSIONS_SERVICE = 'PERMISSIONS_SERVICE';
export const COMMUNICATION_SERVICE = 'COMMUNICATION_SERVICE';